// Generated by CoffeeScript 1.9.3
(function() {
  var random_message;

  random_message = ["トゥットゥルー♪　まゆしぃです", "おかりーん！", "でもまゆしぃはおかりんの人質なので〜", "ゲルバナはデロデロでプニュプニュだったよ"];

  module.exports = function(robot) {
    robot.hear(/:mayuri|@mayuri/, function(msg) {
      return msg.send(msg.random(random_message));
    });
    robot.hear(/とぅっとぅるー|トゥットゥルー/i, function(msg) {
      return msg.send(msg.random(["トゥットゥルー♪　まゆしぃです", "トゥットゥルー♪"]));
    });
    robot.hear(/鳳凰院|凶真/i, function(msg) {
      return msg.send(msg.random(["おかりんの方が可愛いのに〜"]));
    });
    robot.hear(/タイムマシン/i, function(msg) {
      return msg.send(msg.random(["タイムマシン！凄いね〜"]));
    });
    return robot.hear(/ドクペ|ドクター.*ペッパー/i, function(msg) {
      return msg.send(msg.random(["本当にドクペが好きだよね〜"]));
    });
  };

}).call(this);
